apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview
  labels:
    app: interview
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: interview
  template:
    metadata:
      labels:
        app: interview
    spec:
      containers:
        - name: interview #The name of the container
          image: alvonellos/interview:$BUILD_NUMBER #The Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8009
              hostPort: 8009
              hostIP: 0.0.0.0
              protocol: "TCP"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: TOKEN

