apiVersion: v1
kind: Service
metadata:
  name: interview #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: interview
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.79
  loadBalancerIP: 192.168.0.79
  ports:
    - port: 80 #Service port
      targetPort: 8082
      protocol: TCP #The port for the container