apiVersion: v1
kind: Service
metadata:
  name: interview #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: interview
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 172.16.253.9
  loadBalancerIP: 172.16.253.9
  ports:
    - port: 80 #Service port
      targetPort: 8009
      protocol: TCP #The port for the container